// internal/reporter/reporter.go
package reporter

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/SUNmingfeng/github-sentinel/internal/github"
	"github.com/SUNmingfeng/github-sentinel/internal/llm"
)

type Reporter struct {
	githubClient *github.Client
	llmClient    *llm.DeepSeekClient
	dailyDir     string
	reportDir    string
}

func NewReporter(githubClient *github.Client, llmClient *llm.DeepSeekClient, dailyDir, reportDir string) *Reporter {
	return &Reporter{
		githubClient: githubClient,
		llmClient:    llmClient,
		dailyDir:     dailyDir,
		reportDir:    reportDir,
	}
}

// GenerateAIDailyReport 生成 AI 增强的每日报告
func (r *Reporter) GenerateAIDailyReport(ctx context.Context, repoFullName string) error {
	// 1. 先获取原始数据
	owner, repo := parseRepoFullName(repoFullName)

	issues, err := r.githubClient.GetRecentIssues(ctx, owner, repo, 1)
	if err != nil {
		return fmt.Errorf("failed to get issues: %w", err)
	}

	pulls, err := r.githubClient.GetRecentPullRequests(ctx, owner, repo, 1)
	if err != nil {
		return fmt.Errorf("failed to get pull requests: %w", err)
	}

	// 2. 生成原始 Markdown 内容
	rawContent := r.formatRawContent(repoFullName, issues, pulls)

	// 3. 保存原始每日进展文件
	dailyFilename := fmt.Sprintf("%s_%s.md",
		strings.ReplaceAll(repoFullName, "/", "_"),
		time.Now().Format("20060102"))
	dailyPath := filepath.Join(r.dailyDir, dailyFilename)
	if err := os.WriteFile(dailyPath, []byte(rawContent), 0644); err != nil {
		return fmt.Errorf("failed to save daily progress: %w", err)
	}
	fmt.Printf("✓ Daily progress saved to %s\n", dailyPath)

	// 4. 调用 DeepSeek 生成 AI 报告
	fmt.Println("🤖 Generating AI-powered report...")

	aiReport, err := r.llmClient.GenerateDailyReport(ctx, repoFullName, rawContent)
	if err != nil {
		// 如果 AI 调用失败，回退到原始报告
		fmt.Printf("⚠️ AI generation failed: %v, using fallback\n", err)
		aiReport = r.generateFallbackReport(repoFullName, issues, pulls)
	}

	// 5. 保存最终报告
	reportFilename := fmt.Sprintf("%s_ai_report_%s.md",
		strings.ReplaceAll(repoFullName, "/", "_"),
		time.Now().Format("20060102"))
	reportPath := filepath.Join(r.reportDir, reportFilename)

	finalReport := r.buildFinalReport(repoFullName, aiReport)
	if err := os.WriteFile(reportPath, []byte(finalReport), 0644); err != nil {
		return fmt.Errorf("failed to save report: %w", err)
	}

	fmt.Printf("✓ AI Report saved to %s\n", reportPath)
	return nil
}

// formatRawContent 格式化原始内容
func (r *Reporter) formatRawContent(repoName string, issues []github.IssueInfo, pulls []github.PullRequestInfo) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Raw Data: %s\n\n", repoName))
	sb.WriteString(fmt.Sprintf("**Generated:** %s\n\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString("---\n\n")

	// Issues 数据
	sb.WriteString("## Issues\n\n")
	for _, issue := range issues {
		sb.WriteString(fmt.Sprintf("### #%d: %s\n", issue.Number, issue.Title))
		sb.WriteString(fmt.Sprintf("- State: %s\n", issue.State))
		sb.WriteString(fmt.Sprintf("- Author: @%s\n", issue.Author))
		sb.WriteString(fmt.Sprintf("- Labels: %s\n", strings.Join(issue.Labels, ", ")))
		sb.WriteString(fmt.Sprintf("- URL: %s\n\n", issue.URL))
	}

	// PRs 数据
	sb.WriteString("## Pull Requests\n\n")
	for _, pr := range pulls {
		sb.WriteString(fmt.Sprintf("### #%d: %s\n", pr.Number, pr.Title))
		sb.WriteString(fmt.Sprintf("- State: %s\n", pr.State))
		sb.WriteString(fmt.Sprintf("- Merged: %v\n", pr.Merged))
		sb.WriteString(fmt.Sprintf("- Author: @%s\n", pr.Author))
		sb.WriteString(fmt.Sprintf("- Changes: +%d/-%d\n", pr.Additions, pr.Deletions))
		sb.WriteString(fmt.Sprintf("- URL: %s\n\n", pr.URL))
	}

	return sb.String()
}

// buildFinalReport 构建最终报告
func (r *Reporter) buildFinalReport(repoName, aiContent string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# 🤖 AI-Powered Daily Report: %s\n\n", repoName))
	sb.WriteString(fmt.Sprintf("**Generated with DeepSeek AI** | **Date:** %s\n\n", time.Now().Format("2006-01-02")))
	sb.WriteString("---\n\n")
	sb.WriteString(aiContent)
	sb.WriteString("\n\n---\n")
	sb.WriteString("*Report generated by GitHub Sentinel with DeepSeek AI*\n")

	return sb.String()
}

// generateFallbackReport 降级报告（当 AI 不可用时）
func (r *Reporter) generateFallbackReport(repoName string, issues []github.IssueInfo, pulls []github.PullRequestInfo) string {
	var sb strings.Builder

	openIssues := 0
	for _, issue := range issues {
		if issue.State == "open" {
			openIssues++
		}
	}

	openPRs := 0
	for _, pr := range pulls {
		if pr.State == "open" && !pr.Merged {
			openPRs++
		}
	}

	sb.WriteString(fmt.Sprintf("## 📊 Summary for %s\n\n", repoName))
	sb.WriteString(fmt.Sprintf("- **Open Issues:** %d\n", openIssues))
	sb.WriteString(fmt.Sprintf("- **Open Pull Requests:** %d\n\n", openPRs))

	sb.WriteString("### Recent Activity\n\n")
	sb.WriteString("Please check the daily progress file for detailed information.\n")

	return sb.String()
}

func parseRepoFullName(fullName string) (owner, repo string) {
	parts := strings.Split(fullName, "/")
	if len(parts) == 2 {
		return parts[0], parts[1]
	}
	return "", fullName
}
