// internal/aggregator/aggregator.go
package aggregator

import (
	"fmt"
	"strings"
	"time"

	"github.com/SUNmingfeng/github-sentinel/internal/domain"
)

type Aggregator struct{}

func NewAggregator() *Aggregator {
	return &Aggregator{}
}

func (a *Aggregator) GenerateReport(repoName string, release *domain.Release, events []domain.RepoEvent) string {
	var report strings.Builder

	// 报告头部
	report.WriteString(fmt.Sprintf("# GitHub Sentinel Report\n\n"))
	report.WriteString(fmt.Sprintf("**Repository:** %s\n", repoName))
	report.WriteString(fmt.Sprintf("**Generated:** %s\n\n", time.Now().Format("2006-01-02 15:04:05")))
	report.WriteString("---\n\n")

	// 最新版本信息
	if release != nil {
		report.WriteString("## 🚀 Latest Release\n\n")
		report.WriteString(fmt.Sprintf("**Version:** %s\n", release.TagName))
		if release.Name != "" {
			report.WriteString(fmt.Sprintf("**Name:** %s\n", release.Name))
		}
		report.WriteString(fmt.Sprintf("**Published:** %s\n", release.PublishedAt.Format("2006-01-02")))
		report.WriteString(fmt.Sprintf("**URL:** %s\n\n", release.URL))

		if release.Body != "" {
			report.WriteString("### Release Notes\n\n")
			report.WriteString(release.Body)
			report.WriteString("\n\n")
		}
	}

	// 按类型分组统计
	eventMap := make(map[string][]domain.RepoEvent)
	for _, event := range events {
		eventMap[event.Type] = append(eventMap[event.Type], event)
	}

	// 提交记录
	if commits, ok := eventMap["commit"]; ok && len(commits) > 0 {
		report.WriteString(fmt.Sprintf("## 📝 Recent Commits (%d)\n\n", len(commits)))
		for i, commit := range commits {
			if i >= 10 { // 只显示最近10条
				report.WriteString(fmt.Sprintf("... and %d more commits\n\n", len(commits)-10))
				break
			}
			report.WriteString(fmt.Sprintf("- `%s` - %s\n", commit.Title, commit.Author))
		}
		report.WriteString("\n")
	}

	// Pull Requests
	if pulls, ok := eventMap["pull_request"]; ok && len(pulls) > 0 {
		report.WriteString(fmt.Sprintf("## 🔀 Pull Requests (%d)\n\n", len(pulls)))
		for _, pull := range pulls {
			report.WriteString(fmt.Sprintf("- [%s] %s\n", pull.Author, pull.Title))
		}
		report.WriteString("\n")
	}

	// Issues
	if issues, ok := eventMap["issue"]; ok && len(issues) > 0 {
		report.WriteString(fmt.Sprintf("## 🐛 Issues (%d)\n\n", len(issues)))
		for _, issue := range issues {
			report.WriteString(fmt.Sprintf("- [%s] %s\n", issue.Author, issue.Title))
		}
		report.WriteString("\n")
	}

	// 统计摘要
	report.WriteString("## 📊 Summary\n\n")
	report.WriteString(fmt.Sprintf("- **Total Updates:** %d\n", len(events)))
	report.WriteString(fmt.Sprintf("- **Commits:** %d\n", len(eventMap["commit"])))
	report.WriteString(fmt.Sprintf("- **Pull Requests:** %d\n", len(eventMap["pull_request"])))
	report.WriteString(fmt.Sprintf("- **Issues:** %d\n\n", len(eventMap["issue"])))

	report.WriteString("---\n")
	report.WriteString("*Generated by GitHub Sentinel*")

	return report.String()
}
